In [1]:
test = "Hello World"
print(test)

Hello World


In [2]:
import numpy as np

# Basics of Numpy #

In [3]:
single = np.array([1, 2, 3])
print(single)

[1 2 3]


In [19]:
single = np.arange(5)
print(single)

single = np.arange(0, 20, 4)
print(single)

single = np.arange(0, 20, 4, dtype=float)
print(single)

[0 1 2 3 4]
[ 0  4  8 12 16]
[ 0.  4.  8. 12. 16.]


In [18]:
lsarray = np.linspace(0, 10, 10)
print(lsarray)

lsarray = np.linspace(0, 10, 10, dtype=int)
print(lsarray)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0  1  2  3  4  5  6  7  8 10]


In [23]:
print(np.ones(5))
print(np.zeros(5))
print(np.empty(5))
print(np.random.rand(5))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0.11784345 0.19936542 0.94922848 0.73441835 0.61405781]


In [24]:
dim2 = np.array([[1, 2, 3], [4, 5, 6]])
print(dim2)

[[1 2 3]
 [4 5 6]]


In [50]:
dim1 = np.arange(1, 24, 2)
dim2 = dim1.reshape(3, 4)
dim3 = dim1.reshape(3, 2, 2)
print(dim1)
print(dim2)
print(dim1.ndim, dim2.ndim, dim3.ndim)
print(dim1.shape, dim2.shape, dim3.shape)
print(dim1.size, dim2.size, dim3.size)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
1 2 3
(12,) (3, 4) (3, 2, 2)
12 12 12


In [48]:
print(dim1[1:4])
print(dim1[1:10:2])
print(dim1[:5])
print(dim1[5:])
print(dim1[::-1])
print(dim1[-1])
print(dim1[::])
print(dim1 == dim1[:])

[3 5 7]
[ 3  7 11 15 19]
[1 3 5 7 9]
[11 13 15 17 19 21 23]
[23 21 19 17 15 13 11  9  7  5  3  1]
23
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[ True  True  True  True  True  True  True  True  True  True  True  True]


In [70]:
print(dim2[1:3])
print(dim2[0:3:2])
print(dim2[0:3:2,0:3:2])
print(dim2[::,0:4:2])
print(dim2[::,:1:-1])

[[ 9 11 13 15]
 [17 19 21 23]]
[[ 1  3  5  7]
 [17 19 21 23]]
[[ 1  5]
 [17 21]]
[[ 1  5]
 [ 9 13]
 [17 21]]
[[ 7  5]
 [15 13]
 [23 21]]


In [84]:
print(dim3[::,::,::-1])

[[[ 3  1]
  [ 7  5]]

 [[11  9]
  [15 13]]

 [[19 17]
  [23 21]]]


In [96]:
print(np.vstack((dim2[::,0:4:2], dim2[::,:1:-1])))
dim21 = np.hstack((dim2[::,0:4:2], dim2[::,:1:-1]))
print(dim21)
print(np.hsplit(dim21, 4))

[[ 1  5]
 [ 9 13]
 [17 21]
 [ 7  5]
 [15 13]
 [23 21]]
[[ 1  5  7  5]
 [ 9 13 15 13]
 [17 21 23 21]]
[array([[ 1],
       [ 9],
       [17]]), array([[ 5],
       [13],
       [21]]), array([[ 7],
       [15],
       [23]]), array([[ 5],
       [13],
       [21]])]


In [97]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [-1.  2.]
